# Generated by Django 5.2.8 on 2026-01-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='logo_cars')),
            ],
        ),
        migrations.CreateModel(
            name='PartPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(default='nothing', max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('condition', models.CharField(choices=[('used', 'Б/у'), ('new', 'Новая')], default='new', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_brand', to='parts.partbrand')),
                ('made_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_place', to='parts.partplace')),
                ('car_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_by_series', to='parts.partseries')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parttype', to='parts.parttype')),
            ],
        ),
    ]
