# Generated by Django 5.2.8 on 2025-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='car_series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partbrand',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
