# Generated by Django 5.2.8 on 2025-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_car_series_alter_partbrand_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='year',
            field=models.DateField(),
        ),
    ]
