# Generated by Django 5.2.8 on 2025-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_part_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='year',
            field=models.IntegerField(),
        ),
    ]
