# Generated by Django 5.2.8 on 2025-11-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_part_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.parttype'),
        ),
    ]
