# Generated by Django 5.2.8 on 2025-11-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_parttype_alter_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partbrand'),
        ),
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partbrand'),
        ),
        migrations.AlterField(
            model_name='part',
            name='car_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_by_series', to='parts.parttype'),
        ),
    ]
