# Generated by Django 5.2.8 on 2025-11-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_parttype_brand_alter_part_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttype',
            name='brand',
        ),
        migrations.CreateModel(
            name='PartSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partbrand')),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='car_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_by_series', to='parts.partseries'),
        ),
    ]
