# Generated by Django 5.2.8 on 2025-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_remove_parttype_brand_partseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
