# Generated by Django 5.2.8 on 2025-11-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_part_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='made_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_place', to='parts.partplace'),
        ),
    ]
