# Generated by Django 5.2.8 on 2025-11-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_partplace_part_used_part_made_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='used',
            new_name='condition',
        ),
    ]
