# Generated by Django 5.2.8 on 2025-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_rename_used_part_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partbrand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partseries',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
