# Generated by Django 5.2.8 on 2025-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_part_slug_partbrand_slug_partseries_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='part_type',
        ),
    ]
