# Generated by Django 5.2.8 on 2025-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_rename_name_part_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
