# Generated by Django 5.2.8 on 2025-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_alter_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('used', 'Б/у'), ('new', 'Новая')], default='new', max_length=10),
        ),
    ]
