# Generated by Django 5.2.8 on 2025-12-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_alter_part_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parttype', to='parts.parttype'),
        ),
    ]
