# Generated by Django 5.2.8 on 2025-12-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_alter_part_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
