# Generated by Django 5.2.8 on 2026-01-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_parttype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_brand', to='parts.partbrand'),
        ),
        migrations.AlterField(
            model_name='partbrand',
            name='picture',
            field=models.ImageField(null=True, upload_to='logo_cars'),
        ),
    ]
