# Generated by Django 5.2.8 on 2026-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_alter_part_brand_alter_partbrand_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partbrand',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
