# Generated by Django 5.2.8 on 2026-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_alter_partbrand_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
